### ISSUE TITLE
What happens exactly by switching the compass and the on/off-button?

### ISSUE THREAD

**Issue by thymjan** [WayneKeenan/picraftzero#49]

**Comment by WayneKeenan** [comment]
When using a browser on a platform that has gyros and exposes those thru the w3c DeviceOrientation JS API then the web client will sent pan/tilt data.  You see a video of it in use [here](https://www.youtube.com/watch?v=pUz_y9WAkc8&feature=youtu.be&t=77)

**Comment by thymjan** [comment]
...and the second icon (on/off) just hides the video stream?

**Comment by WayneKeenan** [comment]
It stops steaming to minimise network bandwidth and Pi resource usage.  Mainly for laggy networks, but also helps if you have concurrent remote web clients.
