### ISSUE TITLE
joystick_0 right/left changed in actual version 

### ISSUE THREAD

**Issue by thymjan** [WayneKeenan/picraftzero#55]
I have to set invert_x_axis=yes for behavior like before.

**Comment by WayneKeenan** [comment]
apologies for this, but when I added the automated web client tests I found a 'feature' and the 'correct' way involved making this 'fix' in this [commit](https://github.com/WayneKeenan/picraftzero/commit/32ead1be4251d03a8edc87a6c2dc970a5ada1e93) which flip the x-axis.

You can add to the config as you have done or switch the left and right id's in your script, as have been done in the examples (in the same commit above)

I'm hoping that will be the last of the axis flip issues.   
Apologies again for this, but things like this will crop up and I'll try to make sure the change log shouts about these kind of breaking changes a bit louder at some point in the future when dev is a bit more stable.
Thanks for trying this out at an early stage, your feedback is important very much appreciated.

Cheers,
Wayne
