### ISSUE TITLE
how to execute things when deamonized script is terminated

### ISSUE THREAD

**Issue by thymjan** [WayneKeenan/picraftzero#56]
How can I executed things (e.g. switch lights off) when the deamonized script is terminated?
Is there an easier way than this:
[http://www.pybloggers.com/2016/02/how-to-always-execute-exit-functions-in-python/
](http://www.pybloggers.com/2016/02/how-to-always-execute-exit-functions-in-python/)?

**Comment by WayneKeenan** [comment]
Not really, do that for now.
