### ISSUE TITLE
HTML 

### ISSUE THREAD

**Issue by rbooth2018** [WayneKeenan/picraftzero#64]
How would I go about running Picraftzero through HTML,  so I could control my robot outside my network.

**Comment by WayneKeenan** [comment]
Do you mean access you robot remotely via your home router when on the internet away from home?

**Comment by rbooth2018** [comment]
Away from home... Do I have to port forward.  Pretty new to robotics and
rapsberry pie.   Also uses the noobs install of rapsbian, your universal
remote works great saved me hours of writing code.  However I have a slight
problem with my adafruit pan tilt mount.  I have the servos plugged in the
0 and 1 sockets. But after a few pan and tilt movements the servos freeze
and I have to restart picraft zero.  Once restarted it does it again...

Any help would be greatly appreciated

Thanks

Ritchie

**Comment by rbooth2018** [comment]
How can I edit servo.py to stop servos returning to centre.  Or could you
maybe add a feature to turn it on and off button with the next update.
Sometime it would be nice to keep my camera pan tilt mount  fixed on a
position.

**Comment by WayneKeenan** [comment]
Please create a new ticket
